### ISSUE TITLE
[example - greet] No Headers returned in http Response 

### ISSUE THREAD

**Issue by david6983** [deislabs/krustlet#471] opened 2021-01-04 14:16 UTC
Hello,

I tried to insert some headers in the response of the [greet](https://github.com/deislabs/krustlet/tree/master/demos/wascc/greet) example but when I look into my response headers with curl there are no headers added !

Here is the code:

```rust
extern crate wascc_actor as actor;

use std::collections::HashMap;

use actor::prelude::*;
use log::{info};

actor_handlers! { codec::http::OP_HANDLE_REQUEST => greet,
codec::core::OP_HEALTH_REQUEST => health }

pub fn greet(_r: codec::http::Request) -> HandlerResult<codec::http::Response> {
    let mut hm = HashMap::new();
    hm.insert("accept".to_string(), "application/json".to_string());
    hm.insert("dummy".to_string(), "value".to_string());

    let res = codec::http::Response {
        status_code: 200,
        status: "OK".to_string(),
        header: hm,
        body: b"Hello, World".to_vec(),
    };

    //println!(&format!("Received HTTP request: {:?}", &r));
    info!("res: {:?}", res);
    Ok(res)
}

pub fn health(_h: codec::core::HealthRequest) -> HandlerResult<()> {
    Ok(())
}
```

And here is the curl response:

```
$curl http://localhost:8080 -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< content-length: 12
< date: Mon, 04 Jan 2021 13:53:16 GMT
<
* Connection #0 to host localhost left intact
Hello, World* Closing connection 0
```

**Comment by VishnuJin** [comment] 2021-01-04 15:50
hi @david6983 
can you please let us know how you are running, like after building your source to wasm module, pushing it to the container registry and then using the newly created image in kubernetes yaml file.

**Comment by david6983** [comment] 2021-01-04 15:52
here is the yaml file:

```
apiVersion: v1
kind: Pod
metadata:
  name: greet
  labels:
    app: greet
spec:
  containers:
    - image: registry.gitlab.com/MYREGISTRY/greet-wascc:v0.5
      imagePullPolicy: Always
      name: greet
      ports:
        - containerPort: 8080
          hostPort: 8080
  nodeSelector:
    beta.kubernetes.io/os: linux
    beta.kubernetes.io/arch: wasm32-wascc
  tolerations:
    - key: "node.kubernetes.io/network-unavailable"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wascc"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wascc"
      effect: "NoSchedule"
```

then I am running `kruslet-wascc` with kind on Mac OS X Catalina

```
krustlet-wascc --node-ip 192.168.0.48 --node-name krustlet --bootstrap-file=~/.krustlet/config/bootstrap.conf
```

**Comment by bacongobbler** [comment] 2021-01-04 16:17
Looks correct according to https://docs.rs/wascc-codec/0.8.1/wascc_codec/http/struct.Request.html. Let us know what you find out.

I would try reproducing the issue with one of the examples at https://github.com/wasmCloud/examples and open a ticket there if you can reproduce the issue using wasmCloud directly.

**Comment by bacongobbler** [comment] 2021-01-04 16:21
First few things I'd try:

- make sure you're using the correct image tag in your pod manifest
- ensure you're pushing the correct .wasm file with `wasm-to-oci`
- test the .wasm file locally using wasmCloud.

**Comment by david6983** [comment] 2021-01-04 16:32
I tried to create a simple wascc host and it works, but it doesn't work on kruslet-wascc

**Comment by bacongobbler** [comment] 2021-01-04 16:35
Okay. Can you provide the image that does not work for you? I can try to reproduce the issue locally.

**Comment by david6983** [comment] 2021-01-04 16:46
https://gitlab.com/david.haioum/greet-wascc/container_registry/1604320

**Comment by bacongobbler** [comment] 2021-01-04 17:10
Thanks.

It turns out that I accidentally booked an extra day of vacation off, so I'll be out for the rest of the day. In the meantime, please feel free to post any updates you have with your findings. I'll try to look more into this tomorrow.

**Comment by VishnuJin** [comment] 2021-01-05 09:28
I tried to run the following in wascc-host 14.0 and i don't see the response headers that were added
`extern crate wascc_actor as actor;
extern crate algos;


#[macro_use]
extern crate log;
extern crate serde;
extern crate wascc_codec;

use actor::prelude::*;
use serde::Serialize;

use algos::numerics::primorial;
use std::collections::HashMap;
actor_handlers! {
    codec::http::OP_HANDLE_REQUEST => primorial_num,
    codec::core::OP_HEALTH_REQUEST => health
}

fn primorial_num(r: codec::http::Request) -> HandlerResult<codec::http::Response> {
    info!("Query String: {}", r.query_string);
    let mut hm = HashMap::new();
    // hm.insert("accept".to_string(), "application/json".to_string());
    // hm.insert("dummy".to_string(), "value".to_string());
    hm.insert(String::from("accept"), String::from("application/json"));
    hm.insert(String::from("dummy"), String::from("value"));

    let p = PrimorialNumberResponse {
        original: r.query_string.to_string(),
        primorial_value: {  
            let s = r.query_string.to_string();
            let n = s.trim().parse::<u128>().unwrap();
            format!("{}",primorial::primorial_big(n))
        }
    };
    let res = codec::http::Response {
        status_code: 200,
        status: "OK".to_string(),
        header: hm,
        body: format!("{:?}",p).as_bytes().to_vec(),
    };

    Ok(res)
    // Ok(codec::http::Response::json(p, 200, "OK"))
}

fn health(_req: codec::core::HealthRequest) -> HandlerResult<()> {
    Ok(())
}

#[derive(Debug, Serialize)]
struct PrimorialNumberResponse {
    original: String,
    primorial_value: String,
}
`
Here is the Curl result
`$ curl localhost:8081?10 -v
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET /?10 HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 66
< date: Tue, 05 Jan 2021 09:19:59 GMT
< 
* Connection #0 to host localhost left intact
PrimorialNumberResponse { original: "10", primorial_value: "210" }`

**Comment by VishnuJin** [comment] 2021-01-05 09:40
I tried running the following actor using wascc-host 14.0 and i don't see the response header that were added
```
extern crate wascc_actor as actor;
extern crate algos;


#[macro_use]
extern crate log;
extern crate serde;
extern crate wascc_codec;

use actor::prelude::*;
use serde::Serialize;

use algos::numerics::primorial;
use std::collections::HashMap;
actor_handlers! {
    codec::http::OP_HANDLE_REQUEST => primorial_num,
    codec::core::OP_HEALTH_REQUEST => health
}

fn primorial_num(r: codec::http::Request) -> HandlerResult<codec::http::Response> {
    info!("Query String: {}", r.query_string);
    let mut hm = HashMap::new();
    // hm.insert("accept".to_string(), "application/json".to_string());
    // hm.insert("dummy".to_string(), "value".to_string());
    hm.insert(String::from("accept"), String::from("application/json"));
    hm.insert(String::from("dummy"), String::from("value"));

    let p = PrimorialNumberResponse {
        original: r.query_string.to_string(),
        primorial_value: {  
            let s = r.query_string.to_string();
            let n = s.trim().parse::<u128>().unwrap();
            format!("{}",primorial::primorial_big(n))
        }
    };
    let res = codec::http::Response {
        status_code: 200,
        status: "OK".to_string(),
        header: hm,
        body: format!("{:?}",p).as_bytes().to_vec(),
    };

    Ok(res)
    // Ok(codec::http::Response::json(p, 200, "OK"))
}

fn health(_req: codec::core::HealthRequest) -> HandlerResult<()> {
    Ok(())
}

#[derive(Debug, Serialize)]
struct PrimorialNumberResponse {
    original: String,
    primorial_value: String,
}
```
here is the Curl response

```
$ curl localhost:8081?10 -v
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8081 (#0)
> GET /?10 HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-length: 66
< date: Tue, 05 Jan 2021 09:39:04 GMT
< 
* Connection #0 to host localhost left intact
PrimorialNumberResponse { original: "10", primorial_value: "210" }
```

**Comment by bacongobbler** [comment] 2021-01-05 18:41
I can also reproduce this issue.

Right now, waSCC is going through a major refactor under [wasmCloud](https://github.com/wasmcloud/). As a result, the [HTTP server provider](https://github.com/wasmCloud/http-server-provider) is now archived and was pulled into the [capability-providers](https://github.com/wasmCloud/capability-providers) repository.

It might be worth looking into https://github.com/wasmCloud/http-server-provider/blob/9208378854fddc994f522b0cd43ea96ab9a0bd6b/src/lib.rs#L231-L239 to see if there's a bug upstream, as that same piece of code [can be found](https://github.com/wasmCloud/capability-providers/blob/48d8d7a86bde1c936ebdc929a7e6581e5d4fbc70/http-server/src/lib.rs#L223-L231) in the new capability provider.

**Comment by david6983** [comment] 2021-01-05 19:28
> I can also reproduce this issue.
> 
> Right now, waSCC is going through a major refactor under [wasmCloud](https://github.com/wasmcloud/). As a result, the [HTTP server provider](https://github.com/wasmCloud/http-server-provider) is now archived and was pulled into the [capability-providers](https://github.com/wasmCloud/capability-providers) repository.
> 
> It might be worth looking into https://github.com/wasmCloud/http-server-provider/blob/9208378854fddc994f522b0cd43ea96ab9a0bd6b/src/lib.rs#L231-L239 to see if there's a bug upstream, as that same piece of code [can be found](https://github.com/wasmCloud/capability-providers/blob/48d8d7a86bde1c936ebdc929a7e6581e5d4fbc70/http-server/src/lib.rs#L223-L231) in the new capability provider.

I see, is kruslet compatible with new wasmCloud actor api ?

**Comment by david6983** [comment] 2021-01-05 22:23
I tried again by compiling `krustlet` from source and I deleted my images on my registry to push again fresh images.

Here are the results:

Code :

```
extern crate wascc_actor as actor;

use std::collections::HashMap;

use actor::prelude::*;
use log::{info};

actor_handlers! { codec::http::OP_HANDLE_REQUEST => greet,
codec::core::OP_HEALTH_REQUEST => health }

pub fn greet(_r: codec::http::Request) -> HandlerResult<codec::http::Response> {
    let mut hm = HashMap::new();
    hm.insert("accept".to_string(), "application/json".to_string());
    hm.insert("dummy".to_string(), "value".to_string());
    hm.insert("dummy2".to_string(), "value2".to_string());

    let res = codec::http::Response {
        status_code: 200,
        status: "OK".to_string(),
        header: hm,
        body: b"Hello, World".to_vec(),
    };

    info!("res: {:?}", res);
    Ok(res)
}

pub fn health(_h: codec::core::HealthRequest) -> HandlerResult<()> {
    Ok(())
}
```

Curl response:

```
$ curl localhost:8006 -v
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8006 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8006 (#0)
> GET / HTTP/1.1
> Host: localhost:8006
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< content-length: 12
< accept: application/json
< dummy: value
< dummy2: value2
< date: Tue, 05 Jan 2021 22:15:40 GMT
<
* Connection #0 to host localhost left intact
Hello, World* Closing connection 0
```

**Comment by david6983** [comment] 2021-01-06 12:52
It seems like the last release of `kruslet-wascc` in the release section has an issue with headers. However if we use the `kruslet-wascc` by compiling from sources using `just run`, headers are correctly returned

**Comment by VishnuJin** [comment] 2021-01-06 13:09
Hi @david6983 
One question though, when I tried with wascc-host 14.0 locally, I weren't able to see the headers. Any idea what I did wrong ? Or is this issue specific to wascc-host version

**Comment by bacongobbler** [comment] 2021-01-06 16:25
Thanks for the report @david6983. Let's close this out as resolved in master. This will be resolved in the next release.

**Closed by bacongobbler** 2021-01-06 16:25 UTC
Labels: question
