### ISSUE TITLE
No command specified error on startup

### ISSUE THREAD

**Issue by DerekStrickland** [deislabs/krustlet#328] opened 2020-07-17 12:56 UTC
Working through the first app 1, 2, 3 tutorial and pod is failing to launch.  Not sure if this is a known issue or just user error on my part ( probably the latter :P ).

`krusty                                                            0/1     CreateContainerError   0          14m`

Event stream shows.

`Error: failed to generate container "<omitted>" spec: no command specified, (via Pod krusty)`

**Comment by bacongobbler** [comment] 2020-10-28 17:54
I just tried walking through the tutorial and could not reproduce this issue with the latest canary release. I'm going to close this for now assuming that it's been resolved in more recent releases. Let us know if you run into this again. Thanks for the report!

**Closed by bacongobbler** 2020-10-28 17:54 UTC
Labels: bug
